import turtle as trtl

painter = trtl.Turtle()

painter.hideturtle()
painter.speed(5)
painter.pensize(5)
painter.turtlesize(5)
painter.pencolor("red")
painter.fillcolor("red")
painter.forward(100)
painter.right(90)
painter.pencolor("green")
painter.fillcolor("green")
painter.forward(100)
painter.right(90)
painter.pencolor("blue")
painter.fillcolor("blue")
painter.forward(100)
painter.right(90)
painter.pencolor("yellow")
painter.fillcolor("yellow")
painter.forward(100)
painter.right(90)
painter.penup()
painter.forward(-100)
painter.pendown()
painter.pencolor("magenta")
painter.fillcolor("magenta")
painter.circle(100)
painter.penup()
painter.forward(300)
painter.pendown()
painter.pencolor("cyan")
painter.fillcolor("cyan")
painter.circle(100)

wn = trtl.Screen()
wn.mainloop()